In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [5]:
data = pd.DataFrame({
    'Color': ['Red', 'Green', 'Blue', 'Green', 'Red']   
})

data

   Color
0    Red
1  Green
2   Blue
3  Green
4    Red

In [6]:
le = LabelEncoder()
data['Color_Encoder'] = le.fit_transform(data['Color'])

data

   Color  Color_Encoder
0    Red              2
1  Green              1
2   Blue              0
3  Green              1
4    Red              2

In [8]:
Encoded_data = pd.get_dummies(data,columns=['Color'])
Encoded_data

   Color_Encoder  Color_Blue  Color_Green  Color_Red
0              2       False        False       True
1              1       False         True      False
2              0        True        False      False
3              1       False         True      False
4              2       False        False       True